spring.application.name=inventra-backend

# DATABASE CONFIGURATION

spring.datasource.url=jdbc:mysql://localhost:3306/inventra?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=SCT121-C004-0434-2023m

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# JWT CONFIGURATION
jwt.secret=ZmY3M2JjY2IxMzFlMjhjODRjZTZiODFkYjQ3YjIwZTA4MTRjYTU4MTNlZmM2NjVkODNhOTQ2YjAxMjJhOTVmOA==
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000


# SERVER
server.port=8080
